apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.backend.maxUploadSizeBytes | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
  name: edgehog-ingress
  namespace: {{ .Values.namespace | quote | default "edgehog" }}
spec:
  rules:
  - host: {{ .Values.frontend.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: edgehog-frontend
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: {{ .Values.backend.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: edgehog-backend
            port:
              number: 4000
        path: /
        pathType: Prefix
  - host: {{ .Values.deviceForwarder.host | quote }}
    http:
      paths:
      - backend:
          service:
            name: edgehog-device-forwarder
            port:
              number: 4000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ .Values.frontend.host | quote }}
    - {{ .Values.backend.host | quote }}
    - {{ .Values.deviceForwarder.host | quote }}
    secretName: tls-secret