apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace | default "edgehog" }}
spec:
  secretName: tls-secret
  dnsNames:
  - {{ .Values.frontend.host | quote }}
  - {{ .Values.backend.host | quote }}
  - {{ .Values.deviceForwarder.host | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt

